### ISSUE TITLE
Update Documentation for Android

### ISSUE THREAD

**Issue by biolan** [evgeni/qifi#23]
Currently available with Galaxy S9/S9+/Note8/S8/S8+/A7 2018/A5 2018/J7+ and W2018(China) or later have integrated QR reading capabilities using Bixby

**Comment by barakplasma** [comment]
Also the Galaxy S10 & S10+

**Comment by evgeni** [comment]
Also "bixby vision" and all Android 11 phones.

**Comment by kohenkatz** [comment]
Android 10 (and newer) has built-in support for scanning Wi-Fi QR codes by tapping the QR Code icon at the bottom of the available network list. It also supports scanning them directly from the camera app if you turn on "Lens" in the camera settings.

**Comment by evgeni** [comment]
done in 257b6723f47af3b8c5a6dc78e23c29311f0fec0d
