### ISSUE TITLE
SSL certificate invalid

### ISSUE THREAD

**Issue by BrainBacon** [evgeni/qifi#28]
I am getting an insecure page warning when visiting the site at `https://qifi.org/`

You should consider using GH-Pages integrated SSL Certificate [documentation found here](https://help.github.com/en/articles/securing-your-github-pages-site-with-https).

**Comment by evgeni** [comment]
Hey,

I've moved the site away from GH Pages to Netlify and there was a moment where the cert was not set up properly.

It works fine for me again. Can you confirm?

**Comment by BrainBacon** [comment]
Looks good to me 👍
