### ISSUE TITLE
WPA3

### ISSUE THREAD

**Issue by ericsong0226** [evgeni/qifi#40]
Can it support WPA3 encryption? If not, can this feature be added?

**Comment by evgeni** [comment]
Just use WPA2, the string is the same. I shall add it to the interface.

**Comment by ericsong0226** [comment]
Do you mean that your project supports WPA3 encryption?

**Comment by ericsong0226** [comment]
There seems to be a problem with your program. After I run it, I cannot generate a QR code.

**Comment by evgeni** [comment]
> Do you mean that your project supports WPA3 encryption?

My project doesn't support encryption as such, it just generates a QR code that contains the encryption type and the password. The encryption type is "WPA" regardless of the version (1, 2, 3).

So your device should be able to connect to a WPA3 protected network just fine.

**Comment by evgeni** [comment]
> There seems to be a problem with your program. After I run it, I cannot generate a QR code.

That's not enough data to help you :)

**Comment by evgeni** [comment]
added "WPA3" to the dropdown in 55a69eb6b160578d97e7b8d5fc4438a930b24506
