### ISSUE TITLE
NPM publication

### ISSUE THREAD

**Issue by rafaellehmkuhl** [evgeni/qifi#42]
Any chance to publish this package in NPM?

**Comment by evgeni** [comment]
There is no package here, so not sure what to publish?

The main thing is the HTML that makes it usable, and that's not for npm?

**Comment by rafaellehmkuhl** [comment]
> There is no package here, so not sure what to publish?
> 
> The main thing is the HTML that makes it usable, and that's not for npm?

My bad. At a first glance I thought this was a library 😅

**Comment by evgeni** [comment]
It's not, no. It's mostly using jQuery and a few plugins to generate QR codes. The "own" portion of JS code is rather minimal.
