### ISSUE TITLE
Jquery not defined

### ISSUE THREAD

**Issue by inktrap** [evgeni/qifi#8]
Jquery is not defined, which results in:

```
Error: Bootstrap's JavaScript requires jQuery  bootstrap.min.js:6:37
ReferenceError: jQuery is not defined[Learn More]  jquery.qrcode.min.js:28:1
ReferenceError: jQuery is not defined[Learn More]  jquery.storage.js:82:1
ReferenceError: $ is not defined[Learn More]  127.0.0.1:8000:242:9
```

Here is the inclusion:

```
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
```

Obviously this would be easily fixed by using the full path.

So, it would be nicer (in a "this is running standalone" sense) to include jquery as a submodule too, or use [Subresource Integrity](https://w3c.github.io/webappsec-subresource-integrity/).

After all my use case is that I don't want to use some kind of shady web service to generate my qrcode, why should I want (untrusted) external scripts?

**Comment by evgeni** [comment]
Hey,

perfectly valid points :)
Sadly jQuery does not ship a built version in their Git, so "just" adding a submodule will not help, one would need to build jQuery (which I'd like to avoid).

Let's look into subresource integrity then.

Thanks for the pointers!

**Comment by inktrap** [comment]
Hi,

the basic version is easy:

    <script src="https://code.jquery.com/jquery-1.10.2.min.js"
    integrity="ni:///sha-256;C6CB9UYIS9UJeqinPHWTHVqh_E1uhG5Twh-Y5qFQmYg?ct=application/javascript">

Where integrity consists of a ni (named information) entry (key, value)
and ct specifies the content type of the resource. So sha256sum it is.

Obviously a fallback should be considered and one should test this too, but:

> Subresource integrity is only supported by the latest browsers. Its will (sic!)
> under heavy development. But you can start using it write away as
> non-supporting browsers will cause no harm.

This was 2 years ago and sounds good, even if you don't like the (intended?) pun.  :)
Source: <http://qnimate.com/how-to-make-browsers-verify-fetched-resources-content/>
I guess there are no excuses anymore.

Excerpts from Evgeni Golov's message of 2017-01-16 14:23:46 -0800:
> Hey,
> 
> perfectly valid points :)
> Sadly jQuery does not ship a built version in their Git, so "just" adding a submodule will not help, one would need to build jQuery (which I'd like to avoid).
> 
> Let's look into subresource integrity then.
> 
> Thanks for the pointers!
>
